### ISSUE TITLE
Changes to passwordmanager

### ISSUE THREAD

**Issue by Lumb-Chul** [cutealism/so-you-want-to-fight-the-state#1]
Currently only Lastpass a cloud based passwordmanager is only being recommended. I would like to add Keepass and Keepassx to other managers as they are managers that save your passwords to a local database rather then a cloud based service which is something you have much more control over. An additional question could be asked if you don't make backups or just rather find the idea of having your passwords accessible anywhere.

**Comment by mfc** [comment]
yes specifically keepassx. added here: https://github.com/cutealism/so-you-want-to-fight-the-state/pull/4

**Comment by imightbeamy** [comment]
This has been merged!
